'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :2.0.50727.3053
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _9fal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9fal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9falOVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("9falOVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property agen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property agen1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agen1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ajouter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ajouter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ball_info_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ball-info-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ball_Reduire_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ball-Reduire-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ball_reduire2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ball-reduire2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ball_stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ball-stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Ball_stop_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ball-stop-64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bureau11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bureau11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cmdaff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmdaff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delRerservation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delRerservation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Help_64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Help_64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property iconinfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("iconinfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property listchercher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listchercher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property modifier() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("modifier", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Precedent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Precedent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Quit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Quit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quitter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quitter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property recherche() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recherche", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vider() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vider", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
